version: '3.9'
services:
    app:
        build:
            context: devops/python/
        container_name: ci_app
        ports:
            - 5000:5000
        volumes:
            - .:/code
        depends_on:
            - db
        networks:
            - ci_network
    
    db:
        container_name: ci_db
        image: mysql:8.0
        env_file:
          - .env
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        networks:
            - ci_network
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
  mysqldata:

networks: 
  ci_network:
    driver: bridge