services:
    app:
        build:
            context: devops/python/
        container_name: ci_app
        ports:
            - 5000:5000
        volumes:
            - .:/code
        depends_on:
            db:
                condition: service_healthy
        networks:
            - ci_network
    
    db:
        container_name: ci_db
        image: mysql:8.0
        ports:
            - "3306:3306"
        networks:
            - ci_network
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        volumes:
            - mysqldata:/var/lib/mysql
        healthcheck:            
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 55

volumes:
  mysqldata:

networks: 
  ci_network:
    driver: bridge